In [1]:
import pandas as pd
df = pd.read_csv('titanic.csv', usecols=['Pclass','Age','Fare','Survived'])

In [2]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  34.5   7.8292
1         1       3  47.0   7.0000
2         0       2  62.0   9.6875
3         0       3  27.0   8.6625
4         1       3  22.0  12.2875

In [3]:
df.head(50)

    Survived  Pclass   Age      Fare
0          0       3  34.5    7.8292
1          1       3  47.0    7.0000
2          0       2  62.0    9.6875
3          0       3  27.0    8.6625
4          1       3  22.0   12.2875
5          0       3  14.0    9.2250
6          1       3  30.0    7.6292
7          0       2  26.0   29.0000
8          1       3  18.0    7.2292
9          0       3  21.0   24.1500
10         0       3   NaN    7.8958
11         0       1  46.0   26.0000
12         1       1  23.0   82.2667
13         0       2  63.0   26.0000
14         1       1  47.0   61.1750
15         1       2  24.0   27.7208
16         0       2  35.0   12.3500
17         0       3  21.0    7.2250
18         1       3  27.0    7.9250
19         1       3  45.0    7.2250
20         0       1  55.0   59.4000
21         0       3   9.0    3.1708
22         1       1   NaN   31.6833
23         0       1  21.0   61.3792
24         1       1  48.0  262.3750
25         0       3  50.0   14.5000
26         1       1  22.0   61.9792
27         0       3  22.5    7.2250
28         0       1  41.0   30.5000
29         0       3   NaN   21.6792
30         0       2  50.0   26.0000
31         0       2  24.0   31.5000
32         1       3  33.0   20.5750
33         1       3   NaN   23.4500
34         0       1  30.0   57.7500
35         0       3  18.5    7.2292
36         1       3   NaN    8.0500
37         1       3  21.0    8.6625
38         0       3  25.0    9.5000
39         0       3   NaN   56.4958
40         0       3  39.0   13.4167
41         0       1   NaN   26.5500
42         0       3  41.0    7.8500
43         1       2  30.0   13.0000
44         1       1  45.0   52.5542
45         0       3  25.0    7.9250
46         0       1  45.0   29.7000
47         0       3   NaN    7.7500
48         1       1  60.0   76.2917
49         1       3  36.0   15.9000

In [4]:
df.tail()

     Survived  Pclass   Age      Fare
413         0       3   NaN    8.0500
414         1       1  39.0  108.9000
415         0       3  38.5    7.2500
416         0       3   NaN    8.0500
417         0       3   NaN   22.3583

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  418 non-null    int64
 1   Pclass    418 non-null    int64
 2   Age       332 non-null    float64
 3   Fare      417 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 13.2 KB

In [6]:
df.describe()

         Survived      Pclass         Age        Fare
count  418.000000  418.000000  332.000000  417.000000
mean     0.363636    2.265550   30.272590   35.627188
std      0.481622    0.841838   14.181209   55.907576
min      0.000000    1.000000    0.170000    0.000000
25%      0.000000    1.000000   21.000000    7.895800
50%      0.000000    3.000000   27.000000   14.454200
75%      1.000000    3.000000   39.000000   31.500000
max      1.000000    3.000000   76.000000  512.329200

In [7]:
df['Age'].fillna(df.Age.median(),inplace=True)

In [8]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
Fare        1
dtype: int64

In [9]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [10]:
X

     Pclass   Age      Fare
0         3  34.5    7.8292
1         3  47.0    7.0000
2         2  62.0    9.6875
3         3  27.0    8.6625
4         3  22.0   12.2875
..      ...   ...       ...
413       3  27.0    8.0500
414       1  39.0  108.9000
415       3  38.5    7.2500
416       3  27.0    8.0500
417       3  27.0   22.3583

[418 rows x 3 columns]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
X_train

     Pclass   Age      Fare
109       2  18.5   13.0000
176       2  20.0   36.7500
366       3  27.0   14.4583
407       1  50.0  211.5000
280       3  23.0    8.6625
..      ...   ...       ...
71        3  21.0    7.8958
106       3  21.0    7.8208
270       1  46.0   75.2417
348       2  24.0   13.5000
102       3  27.0    7.7500

[280 rows x 3 columns]

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler=StandardScaler()

In [16]:
### fit vs fit_transform
X_train_scaled=scaler.fit_transform(X_train)

In [17]:
X_train_scaled

array([[-3.17799463e-01, -8.70240411e-01, -4.08000550e-01],
       [-3.17799463e-01, -7.56249695e-01, -1.13575183e-02],
       [ 8.68651866e-01, -2.24293019e-01, -3.83645833e-01],
       [-1.50425079e+00,  1.52356463e+00,  2.90710016e+00],
       [ 8.68651866e-01, -5.28268262e-01, -4.80440093e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.93244565e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.04377292e-01],
       [-3.17799463e-01,  7.96822248e-02, -2.74394476e-01],
       [-1.50425079e+00,  3.83657468e-01,  2.90710016e+00],
       [-1.50425079e+00,  2.31669847e-01, -1.62152014e-01],
       [-3.17799463e-01, -7.23053970e-02, -1.90890680e-01],
       [ 8.68651866e-01,  4.59651279e-01, -4.66453208e-01],
       [-1.50425079e+00,  5.35645090e-01,  7.63696327e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [-1.50425079e+00,  1.37157701e+00,  6.97589711e-01],
       [-1.50425079e+00,  2.20750893e+00,  2.34631305e-01],
       [-1.50425079e+00,  1.82753987e+00,  3.00808063e-01],
       [-1.50425079e+00,  2.31669847e-01, -1.81705263e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.90669308e-01],
       [ 8.68651866e-01,  7.63626523e-01,  1.58155188e-01],
       [ 8.68651866e-01, -2.21305105e+00, -4.68958321e-01],
       [ 8.68651866e-01, -5.28268262e-01, -3.92969867e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.90669308e-01],
       [-3.17799463e-01,  3.68841389e-03, -3.93666289e-01],
       [-1.50425079e+00,  4.59651279e-01,  3.75675128e+00],
       [ 8.68651866e-01, -2.24293019e-01, -4.95191874e-01],
       [-3.17799463e-01, -1.66817543e+00, -1.90890680e-01],
       [-3.17799463e-01, -1.66817543e+00, -8.23357451e-02],
       [ 8.68651866e-01,  3.68841389e-03, -4.97696988e-01],
       [ 8.68651866e-01, -2.24293019e-01,  5.36427385e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.90669308e-01],
       [-1.50425079e+00,  9.15614144e-01, -1.81705263e-01],
       [-1.50425079e+00, -5.28268262e-01,  7.63696327e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.93244565e-01],
       [ 8.68651866e-01, -7.56249695e-01, -5.04447435e-01],
       [ 8.68651866e-01, -3.00286830e-01, -4.95262017e-01],
       [-1.50425079e+00,  2.81545942e+00,  3.07877060e+00],
       [-3.17799463e-01,  4.59651279e-01, -4.08000550e-01],
       [-3.17799463e-01, -7.23053970e-02, -2.40992958e-01],
       [ 8.68651866e-01, -9.08237317e-01, -5.10218215e-02],
       [ 8.68651866e-01, -1.28820637e+00, -2.86920046e-01],
       [-1.50425079e+00, -6.80255884e-01, -1.81705263e-01],
       [-3.17799463e-01, -9.08237317e-01, -4.08000550e-01],
       [-3.17799463e-01, -6.80255884e-01, -4.08000550e-01],
       [-1.50425079e+00, -2.24293019e-01,  3.50867487e+00],
       [-3.17799463e-01, -2.12413829e+00, -2.40992958e-01],
       [-3.17799463e-01, -9.08237317e-01, -4.49752448e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.08205106e-01],
       [ 8.68651866e-01, -7.23053970e-02, -2.57276198e-01],
       [ 8.68651866e-01, -6.04262073e-01, -4.90669308e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.99019688e-01],
       [-1.50425079e+00, -2.24293019e-01,  2.43329060e-01],
       [-1.50425079e+00,  2.28350274e+00,  3.76718926e+00],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [ 8.68651866e-01, -1.48299208e-01, -5.04029916e-01],
       [-1.50425079e+00,  3.49940371e+00,  6.91744446e-01],
       [-3.17799463e-01, -1.48299208e-01, -1.90890680e-01],
       [-1.50425079e+00,  1.14359558e+00,  3.75675128e+00],
       [ 8.68651866e-01, -7.23053970e-02, -4.92756903e-01],
       [ 8.68651866e-01, -6.04262073e-01, -4.95262017e-01],
       [-1.50425079e+00,  7.96822248e-02, -1.48512504e-01],
       [-1.50425079e+00, -6.80255884e-01,  3.99968821e-01],
       [ 8.68651866e-01, -6.80255884e-01, -4.80440093e-01],
       [-1.50425079e+00,  9.15614144e-01, -1.81705263e-01],
       [-1.50425079e+00,  3.83657468e-01,  3.39358426e-01],
       [ 8.68651866e-01, -6.80255884e-01, -4.94914641e-01],
       [-1.50425079e+00,  1.29558320e+00,  3.17472982e+00],
       [-1.50425079e+00, -9.08237317e-01,  2.61699895e-01],
       [-1.50425079e+00,  1.29558320e+00,  8.30017714e-02],
       [ 8.68651866e-01, -3.76280640e-01, -4.93244565e-01],
       [ 8.68651866e-01, -4.52274451e-01, -4.69375840e-01],
       [-1.50425079e+00,  1.37157701e+00,  1.15226788e+00],
       [ 8.68651866e-01, -2.24293019e-01, -2.33477616e-01],
       [ 8.68651866e-01, -8.32243506e-01, -3.62212079e-01],
       [-1.50425079e+00,  1.52356463e+00,  2.90710016e+00],
       [ 8.68651866e-01, -9.84231127e-01, -3.56228197e-01],
       [-1.50425079e+00, -2.24293019e-01,  2.41032706e-01],
       [-3.17799463e-01, -3.00286830e-01, -4.08000550e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.93521798e-01],
       [-3.17799463e-01, -9.08237317e-01,  6.02395384e-01],
       [ 8.68651866e-01,  8.01623428e-01, -3.72928956e-01],
       [-3.17799463e-01,  1.44757082e+00,  4.60438930e-01],
       [-3.17799463e-01,  9.15614144e-01, -8.23357451e-02],
       [-1.50425079e+00,  1.14359558e+00,  3.66914678e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.93939317e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [ 8.68651866e-01, -7.23053970e-02, -4.93939317e-01],
       [-1.50425079e+00,  3.68841389e-03,  1.34774125e-01],
       [-1.50425079e+00,  6.87632712e-01,  5.65374811e-01],
       [ 8.68651866e-01, -2.24293019e-01, -2.63051321e-01],
       [ 8.68651866e-01, -4.52274451e-01, -4.90669308e-01],
       [ 8.68651866e-01, -3.76280640e-01, -4.66453208e-01],
       [-1.50425079e+00,  1.21958939e+00, -1.90890680e-01],
       [ 8.68651866e-01, -2.12413829e+00, -2.87546324e-01],
       [-3.17799463e-01,  7.63626523e-01, -3.57898272e-01],
       [ 8.68651866e-01, -2.24293019e-01, -3.83714306e-01],
       [-1.50425079e+00,  4.59651279e-01, -9.60437283e-02],
       [-1.50425079e+00,  2.58747798e+00,  7.63696327e-01],
       [-3.17799463e-01, -2.20013210e+00,  6.92937882e-02],
       [-1.50425079e+00,  2.58747798e+00, -1.81705263e-01],
       [ 8.68651866e-01, -1.59218161e+00, -3.70493985e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.04447435e-01],
       [ 8.68651866e-01, -2.20013210e+00, -3.46207741e-01],
       [-1.50425079e+00, -9.08237317e-01,  3.76935134e-01],
       [ 8.68651866e-01,  3.68841389e-03, -5.09040144e-01],
       [-1.50425079e+00, -6.04262073e-01,  3.66914678e-01],
       [-3.17799463e-01,  9.91607955e-01, -2.74394476e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.93521798e-01],
       [ 8.68651866e-01, -1.89615686e+00, -1.00915340e-01],
       [-1.50425079e+00,  1.14359558e+00,  4.33021294e-01],
       [-3.17799463e-01,  8.39620334e-01, -4.08000550e-01],
       [-3.17799463e-01,  7.96822248e-02, -2.74394476e-01],
       [ 8.68651866e-01, -2.62289924e-01, -5.04447435e-01],
       [ 8.68651866e-01, -1.28820637e+00, -1.00915340e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.89625511e-01],
       [ 8.68651866e-01, -9.08237317e-01, -4.95262017e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [-3.17799463e-01,  2.43549036e+00, -4.63321815e-01],
       [ 8.68651866e-01, -6.80255884e-01, -5.16625628e-01],
       [ 8.68651866e-01, -9.08237317e-01, -3.83714306e-01],
       [-3.17799463e-01, -1.36420018e+00, -3.62073462e-01],
       [-1.50425079e+00,  1.75154606e+00, -1.66744722e-01],
       [-3.17799463e-01, -3.76280640e-01, -9.90365043e-02],
       [ 8.68651866e-01, -2.21913055e+00, -3.95057462e-01],
       [ 8.68651866e-01, -2.24293019e-01, -2.36817768e-01],
       [-3.17799463e-01, -3.00286830e-01, -4.08000550e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.98602169e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.17599283e-01],
       [-3.17799463e-01,  1.06760177e+00, -4.08000550e-01],
       [-1.50425079e+00,  1.14359558e+00,  2.52584621e-01],
       [-3.17799463e-01, -2.24293019e-01, -4.10088145e-01],
       [-3.17799463e-01, -2.24293019e-01, -2.74394476e-01],
       [ 8.68651866e-01, -2.24293019e-01, -3.83714306e-01],
       [-1.50425079e+00,  1.14359558e+00,  1.62114170e+00],
       [-3.17799463e-01, -6.80255884e-01, -2.74394476e-01],
       [ 8.68651866e-01, -3.00286830e-01, -3.95057462e-01],
       [-1.50425079e+00, -5.28268262e-01,  7.48805930e-01],
       [ 8.68651866e-01, -8.70240411e-01, -5.04377292e-01],
       [-1.50425079e+00,  8.39620334e-01, -1.15737264e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.99019688e-01],
       [-1.50425079e+00,  2.35949655e+00,  3.75675128e+00],
       [ 8.68651866e-01, -2.24293019e-01, -4.93244565e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.04029916e-01],
       [ 8.68651866e-01, -6.80255884e-01, -4.90669308e-01],
       [ 8.68651866e-01, -3.76280640e-01, -4.94914641e-01],
       [-3.17799463e-01, -2.24293019e-01, -3.74042896e-01],
       [-1.50425079e+00,  1.90353369e+00, -1.62152014e-01],
       [-1.50425079e+00,  1.90353369e+00,  1.64006867e+00],
       [ 8.68651866e-01, -3.00286830e-01, -4.95262017e-01],
       [-3.17799463e-01,  4.59651279e-01,  2.62191900e-02],
       [-1.50425079e+00, -2.24293019e-01, -1.81705263e-01],
       [-3.17799463e-01, -1.36420018e+00,  2.62191900e-02],
       [ 8.68651866e-01,  3.83657468e-01, -4.95679536e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [ 8.68651866e-01,  1.93672941e-01, -4.66453208e-01],
       [ 8.68651866e-01,  6.11638901e-01, -5.04377292e-01],
       [ 8.68651866e-01, -6.04262073e-01, -4.19899841e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [-1.50425079e+00,  1.82753987e+00,  7.41985340e-01],
       [-1.50425079e+00,  9.91607955e-01,  3.00808063e-01],
       [ 8.68651866e-01, -5.28268262e-01, -4.94914641e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.93521798e-01],
       [-3.17799463e-01,  2.28350274e+00, -1.90890680e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.04447435e-01],
       [ 8.68651866e-01, -7.56249695e-01, -4.93939317e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.04377292e-01],
       [-1.50425079e+00,  9.15614144e-01,  8.46718473e-02],
       [-3.17799463e-01,  1.55676036e-01, -3.99650171e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [ 8.68651866e-01,  2.31669847e-01, -2.81492299e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.99019688e-01],
       [ 8.68651866e-01, -2.24293019e-01, -3.66248652e-01],
       [-3.17799463e-01, -7.56249695e-01, -3.93596145e-01],
       [ 8.68651866e-01, -5.66265168e-01, -5.04447435e-01],
       [-3.17799463e-01, -6.80255884e-01, -4.33051689e-01],
       [-3.17799463e-01, -1.21221256e+00,  4.60438930e-01],
       [ 8.68651866e-01,  4.97648185e-01, -3.34517210e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.04377292e-01],
       [-3.17799463e-01, -3.00286830e-01, -3.99650171e-01],
       [-1.50425079e+00,  1.52356463e+00, -1.90890680e-01],
       [ 8.68651866e-01, -5.28268262e-01, -4.90669308e-01],
       [ 8.68651866e-01, -9.08237317e-01, -4.95679536e-01],
       [ 8.68651866e-01, -4.52274451e-01, -4.93939317e-01],
       [-3.17799463e-01,  9.15614144e-01, -4.08000550e-01],
       [ 8.68651866e-01, -9.08237317e-01, -5.04377292e-01],
       [-1.50425079e+00, -1.28820637e+00,  3.75675128e+00],
       [ 8.68651866e-01,  1.55676036e-01, -4.95262017e-01],
       [-1.50425079e+00,  1.29558320e+00,  3.96558526e-01],
       [-1.50425079e+00, -7.23053970e-02,  3.07877060e+00],
       [ 8.68651866e-01,  6.87632712e-01, -4.01041344e-01],
       [ 8.68651866e-01, -8.32243506e-01, -3.56228197e-01],
       [ 8.68651866e-01, -1.17421565e+00,  5.36427385e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.93521798e-01],
       [-3.17799463e-01, -6.04262073e-01, -4.49752448e-01],
       [-3.17799463e-01, -4.52274451e-01, -7.11218533e-03],
       [-1.50425079e+00,  2.58747798e+00,  6.31621712e-01],
       [-3.17799463e-01, -4.52274451e-01, -4.49752448e-01],
       [-3.17799463e-01, -9.84231127e-01,  6.02395384e-01],
       [ 8.68651866e-01, -3.00286830e-01, -4.93244565e-01],
       [ 8.68651866e-01, -3.00286830e-01, -4.93521798e-01],
       [ 8.68651866e-01, -7.56249695e-01, -4.92756903e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.96167198e-01],
       [ 8.68651866e-01, -2.24293019e-01, -3.82949411e-01],
       [ 8.68651866e-01, -4.52274451e-01, -4.80440093e-01],
       [ 8.68651866e-01, -9.84231127e-01, -4.80440093e-01],
       [ 8.68651866e-01, -2.25104795e+00, -3.84619487e-01],
       [ 8.68651866e-01, -1.74416924e+00, -3.70493985e-01],
       [-3.17799463e-01,  3.68841389e-03, -4.08000550e-01],
       [-1.50425079e+00,  2.05552131e+00,  2.12828864e+00],
       [-3.17799463e-01,  3.07663657e-01, -1.90890680e-01],
       [ 8.68651866e-01,  1.14359558e+00, -3.89491099e-01],
       [ 8.68651866e-01, -6.80255884e-01, -4.95262017e-01],
       [ 8.68651866e-01, -1.48299208e-01, -2.48925818e-01],
       [-1.50425079e+00, -1.48299208e-01,  3.76718926e+00],
       [ 8.68651866e-01,  1.29558320e+00, -5.08205106e-01],
       [ 8.68651866e-01,  4.59651279e-01, -3.59568348e-01],
       [ 8.68651866e-01, -1.82016305e+00, -3.70493985e-01],
       [-1.50425079e+00, -2.24293019e-01, -1.95204486e-01],
       [-1.50425079e+00,  3.68841389e-03,  3.39358426e-01],
       [ 8.68651866e-01, -2.20013210e+00, -4.21640060e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95262017e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.04377292e-01],
       [-3.17799463e-01, -7.56249695e-01, -2.40992958e-01],
       [ 8.68651866e-01, -1.06022494e+00, -4.97349612e-01],
       [-3.17799463e-01,  3.68841389e-03, -4.12384499e-01],
       [-3.17799463e-01,  1.14359558e+00, -1.24087643e-01],
       [-3.17799463e-01,  2.51148417e+00, -1.90890680e-01],
       [ 8.68651866e-01, -9.84231127e-01, -4.95958439e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [ 8.68651866e-01, -2.24293019e-01, -3.66248652e-01],
       [-1.50425079e+00,  1.37157701e+00,  2.18207778e-01],
       [-3.17799463e-01, -7.23053970e-02, -1.90890680e-01],
       [-1.50425079e+00,  5.35645090e-01,  8.77957911e-01],
       [ 8.68651866e-01,  9.91607955e-01, -4.93244565e-01],
       [-1.50425079e+00,  3.68841389e-03,  1.90588964e+00],
       [-3.17799463e-01,  6.11638901e-01, -2.74394476e-01],
       [-3.17799463e-01, -6.04262073e-01, -9.90365043e-02],
       [ 8.68651866e-01, -2.24293019e-01, -4.93383182e-01],
       [-3.17799463e-01, -2.24293019e-01, -3.64925952e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.80440093e-01],
       [-1.50425079e+00, -4.52274451e-01,  3.76935134e-01],
       [ 8.68651866e-01,  7.63626523e-01, -1.00915340e-01],
       [-3.17799463e-01,  7.63626523e-01, -4.08000550e-01],
       [ 8.68651866e-01,  6.49635806e-01, -5.04029916e-01],
       [ 8.68651866e-01, -9.84231127e-01, -4.90669308e-01],
       [ 8.68651866e-01, -6.04262073e-01, -4.75429866e-01],
       [ 8.68651866e-01, -2.24293019e-01, -3.56228197e-01],
       [-1.50425079e+00,  2.28350274e+00,  6.49018893e-01],
       [ 8.68651866e-01, -2.24293019e-01, -3.82949411e-01],
       [ 8.68651866e-01, -7.56249695e-01, -4.93939317e-01],
       [-1.50425079e+00, -2.24293019e-01,  1.65920607e+00],
       [ 8.68651866e-01, -1.59218161e+00, -5.72155653e-01],
       [ 8.68651866e-01,  5.35645090e-01, -4.95679536e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95958439e-01],
       [-3.17799463e-01, -1.48299208e-01, -4.49752448e-01],
       [-1.50425079e+00, -2.24293019e-01, -1.90890680e-01],
       [-3.17799463e-01, -4.52274451e-01,  4.60438930e-01],
       [-1.50425079e+00,  1.75154606e+00,  7.41985340e-01],
       [-1.50425079e+00,  2.13151512e+00,  7.93117620e+00],
       [ 8.68651866e-01, -1.48299208e-01, -4.90669308e-01],
       [-1.50425079e+00,  1.90353369e+00,  9.36410568e-01],
       [-3.17799463e-01,  3.68841389e-03, -1.90890680e-01],
       [ 8.68651866e-01,  1.55676036e-01, -4.90669308e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.93244565e-01],
       [ 8.68651866e-01,  3.68841389e-03, -3.65413614e-01],
       [ 8.68651866e-01,  2.31669847e-01, -4.90669308e-01],
       [-1.50425079e+00,  1.44757082e+00, -6.25110420e-01],
       [ 8.68651866e-01, -9.08237317e-01, -4.90669308e-01],
       [-3.17799463e-01,  1.37157701e+00, -1.13575183e-02],
       [ 8.68651866e-01,  6.11638901e-01, -4.95262017e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [ 8.68651866e-01, -2.24293019e-01, -2.51709835e-01],
       [-1.50425079e+00,  1.90353369e+00,  3.66914678e-01],
       [ 8.68651866e-01, -2.24293019e-01,  5.36427385e-01],
       [ 8.68651866e-01, -6.80255884e-01, -4.93244565e-01],
       [ 8.68651866e-01, -6.80255884e-01, -4.94497122e-01],
       [-1.50425079e+00,  1.21958939e+00,  6.31483096e-01],
       [-3.17799463e-01, -4.52274451e-01, -3.99650171e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01]])

In [18]:
X_test_scaled = scaler.transform(X_test)

In [19]:
X_test_scaled

array([[ 8.68651866e-01, -3.76280640e-01, -5.04377292e-01],
       [-1.50425079e+00,  6.87632712e-01,  2.90438628e+00],
       [ 8.68651866e-01, -6.80255884e-01, -4.95679536e-01],
       [ 8.68651866e-01,  3.83657468e-01, -4.93244565e-01],
       [ 8.68651866e-01,  4.59651279e-01, -4.21640060e-01],
       [-3.17799463e-01,  1.52356463e+00, -1.90890680e-01],
       [ 8.68651866e-01, -7.23053970e-02, -4.92756903e-01],
       [-1.50425079e+00,  1.44757082e+00, -1.90890680e-01],
       [-3.17799463e-01, -8.32243506e-01, -4.08000550e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.90669308e-01],
       [ 8.68651866e-01, -6.80255884e-01, -2.21787085e-01],
       [-1.50425079e+00,  1.59955844e+00,  3.28994936e-02],
       [ 8.68651866e-01, -1.06022494e+00, -4.82875064e-01],
       [-1.50425079e+00,  6.87632712e-01,  1.19360226e+00],
       [ 8.68651866e-01, -2.24293019e-01, -4.90669308e-01],
       [ 8.68651866e-01, -2.24293019e-01,  3.18412333e-01],
       [ 8.68651866e-01, -1.48299208e-01, -4.95262017e-01],
       [-1.50425079e+00,  1.90353369e+00,  2.09927542e-01],
       [ 8.68651866e-01, -1.51618780e+00, -1.38700807e-01],
       [-3.17799463e-01, -5.28268262e-01, -4.49752448e-01],
       [-3.17799463e-01,  2.05552131e+00, -4.08000550e-01],
       [-1.50425079e+00,  8.39620334e-01,  2.41032706e-01],
       [ 8.68651866e-01, -2.04814448e+00, -3.95057462e-01],
       [-3.17799463e-01,  3.68841389e-03, -4.08000550e-01],
       [ 8.68651866e-01, -2.24293019e-01, -3.70493985e-01],
       [ 8.68651866e-01, -8.70240411e-01, -5.03473780e-01],
       [-1.50425079e+00, -3.76280640e-01,  3.00808063e-01],
       [-1.50425079e+00, -2.24293019e-01, -1.81705263e-01],
       [ 8.68651866e-01,  6.87632712e-01, -5.04377292e-01],
       [-3.17799463e-01,  3.68841389e-03, -4.08000550e-01],
       [ 8.68651866e-01,  1.55676036e-01, -2.48925818e-01],
       [ 8.68651866e-01, -6.04262073e-01,  3.77009619e-02],
       [-1.50425079e+00,  2.31669847e-01,  1.90588964e+00],
       [ 8.68651866e-01, -2.24293019e-01, -4.90669308e-01],
       [-3.17799463e-01, -6.04262073e-01, -4.49752448e-01],
       [-3.17799463e-01, -3.76280640e-01, -4.49752448e-01],
       [ 8.68651866e-01, -4.52274451e-01, -4.95679536e-01],
       [-3.17799463e-01, -2.24293019e-01, -3.73834137e-01],
       [-3.17799463e-01, -7.23053970e-02, -1.90890680e-01],
       [-1.50425079e+00,  1.93672941e-01,  2.90710016e+00],
       [ 8.68651866e-01, -4.52274451e-01, -4.95679536e-01],
       [ 8.68651866e-01, -2.24293019e-01, -2.33477616e-01],
       [-3.17799463e-01,  8.39620334e-01, -3.73834137e-01],
       [-1.50425079e+00, -2.24293019e-01,  3.62396455e-02],
       [-1.50425079e+00, -1.10302302e-01, -1.62152014e-01],
       [ 8.68651866e-01, -6.80255884e-01, -4.93939317e-01],
       [ 8.68651866e-01, -2.24293019e-01,  5.36427385e-01],
       [-3.17799463e-01, -4.52274451e-01, -1.62152014e-01],
       [-1.50425079e+00,  1.90353369e+00, -1.95900908e-01],
       [ 8.68651866e-01,  4.59651279e-01, -5.04029916e-01],
       [ 8.68651866e-01,  3.45660563e-01, -4.94356836e-01],
       [ 8.68651866e-01,  1.14359558e+00, -5.04447435e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.90669308e-01],
       [-3.17799463e-01,  1.29558320e+00, -4.49752448e-01],
       [-3.17799463e-01, -7.23053970e-02, -3.93666289e-01],
       [-3.17799463e-01, -7.56249695e-01, -1.90890680e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.90669308e-01],
       [-3.17799463e-01, -3.00286830e-01, -4.08000550e-01],
       [ 8.68651866e-01, -2.26320696e+00, -2.81492299e-01],
       [ 8.68651866e-01, -4.52274451e-01, -5.04029916e-01],
       [ 8.68651866e-01,  1.52356463e+00, -3.82949411e-01],
       [-3.17799463e-01, -6.80255884e-01, -4.33051689e-01],
       [-1.50425079e+00, -2.24293019e-01, -1.62152014e-01],
       [-3.17799463e-01,  7.63626523e-01, -1.90890680e-01],
       [-3.17799463e-01, -1.13621875e+00,  2.62191900e-02],
       [-3.17799463e-01, -3.76280640e-01, -4.49752448e-01],
       [ 8.68651866e-01,  8.39620334e-01, -4.94009460e-01],
       [ 8.68651866e-01, -4.52274451e-01, -4.99019688e-01],
       [-1.50425079e+00,  6.87632712e-01, -1.29097871e-01],
       [-1.50425079e+00,  9.91607955e-01, -1.62152014e-01],
       [-1.50425079e+00,  2.05552131e+00,  1.82189818e+00],
       [-3.17799463e-01,  3.68841389e-03, -2.74394476e-01],
       [ 8.68651866e-01,  1.55676036e-01, -4.98532026e-01],
       [-1.50425079e+00, -2.24293019e-01, -9.59752551e-02],
       [-1.50425079e+00,  1.14359558e+00, -1.29097871e-01],
       [ 8.68651866e-01, -6.04262073e-01, -4.80440093e-01],
       [-1.50425079e+00,  3.68841389e-03, -1.90890680e-01],
       [ 8.68651866e-01, -6.04262073e-01, -3.92969867e-01],
       [ 8.68651866e-01, -3.00286830e-01, -2.57276198e-01],
       [ 8.68651866e-01, -3.76280640e-01, -4.97349612e-01],
       [ 8.68651866e-01, -6.04262073e-01, -4.94914641e-01],
       [-1.50425079e+00,  1.37157701e+00,  3.75675128e+00],
       [ 8.68651866e-01, -6.80255884e-01, -5.04447435e-01],
       [ 8.68651866e-01, -9.08237317e-01, -4.93521798e-01],
       [-3.17799463e-01,  1.55676036e-01, -4.08000550e-01],
       [-3.17799463e-01, -4.52274451e-01, -9.90365043e-02],
       [-3.17799463e-01, -2.24293019e-01, -4.46273680e-01],
       [-1.50425079e+00, -4.52274451e-01,  7.48805930e-01],
       [-3.17799463e-01, -8.32243506e-01, -4.49752448e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.07370068e-01],
       [-1.50425079e+00, -3.76280640e-01, -1.90890680e-01],
       [ 8.68651866e-01, -1.82016305e+00, -2.73141919e-01],
       [-1.50425079e+00,  1.21958939e+00,  6.97589711e-01],
       [ 8.68651866e-01, -1.21221256e+00, -4.71045916e-01],
       [ 8.68651866e-01, -3.76280640e-01, -4.92756903e-01],
       [ 8.68651866e-01, -1.51618780e+00,  1.58155188e-01],
       [ 8.68651866e-01,  7.96822248e-02, -3.24496754e-01],
       [-1.50425079e+00, -9.84231127e-01,  1.61495340e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [-3.17799463e-01,  3.83657468e-01, -4.18856044e-01],
       [ 8.68651866e-01, -4.52274451e-01, -4.95262017e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [ 8.68651866e-01, -5.28268262e-01, -5.07370068e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.80440093e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.92756903e-01],
       [ 8.68651866e-01, -2.24293019e-01, -1.99797195e-01],
       [ 8.68651866e-01, -9.84231127e-01, -4.93244565e-01],
       [-3.17799463e-01, -5.28268262e-01, -4.49752448e-01],
       [ 8.68651866e-01, -2.24293019e-01, -5.04447435e-01],
       [ 8.68651866e-01, -6.04262073e-01, -4.96097055e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.93244565e-01],
       [-3.17799463e-01,  2.35949655e+00, -4.18856044e-01],
       [ 8.68651866e-01, -1.40219709e+00, -3.82949411e-01],
       [-1.50425079e+00, -2.24293019e-01, -6.25110420e-01],
       [-1.50425079e+00, -1.82016305e+00,  1.62114170e+00],
       [ 8.68651866e-01, -2.24293019e-01, -5.17599283e-01],
       [-1.50425079e+00, -6.04262073e-01,  4.09989277e-01],
       [-3.17799463e-01, -3.00286830e-01, -1.40788402e-01],
       [-3.17799463e-01, -2.20621161e+00, -1.61664351e-01],
       [-3.17799463e-01, -6.04262073e-01, -2.74394476e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.79605055e-01],
       [-3.17799463e-01, -2.24293019e-01, -1.90890680e-01],
       [ 8.68651866e-01, -9.08237317e-01, -4.80440093e-01],
       [ 8.68651866e-01, -2.24293019e-01, -2.63051321e-01],
       [ 8.68651866e-01,  2.31669847e-01, -4.93939317e-01],
       [-1.50425079e+00, -5.28268262e-01,  9.36410568e-01],
       [-1.50425079e+00,  4.59651279e-01,  6.31483096e-01],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01],
       [-1.50425079e+00,  2.51148417e+00,  3.07877060e+00],
       [ 8.68651866e-01, -6.04262073e-01, -5.04447435e-01],
       [-1.50425079e+00,  1.75154606e+00, -1.49138782e-01],
       [ 8.68651866e-01, -5.28268262e-01, -4.93939317e-01],
       [ 8.68651866e-01,  2.32149965e+00,             nan],
       [-1.50425079e+00,  7.96822248e-02,  1.62114170e+00],
       [ 8.68651866e-01,  7.96822248e-02, -4.95958439e-01],
       [-1.50425079e+00, -3.00286830e-01,  1.65920607e+00],
       [-1.50425079e+00,  3.68841389e-03,  2.12828864e+00],
       [ 8.68651866e-01, -2.24293019e-01, -4.95679536e-01]])

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
classification = LogisticRegression()

In [22]:
classification.fit(X_train_scaled,y_train)

LogisticRegression()

In [ ]:
df_scaled = df_scaled.transform(df)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df_scaled

In [ ]:
plt.hist(df_scaled[:,1],bins=20)

In [ ]:
plt.hist(df_scaled[:,2],bins=20)

In [ ]:
plt.hist(df_scaled[:,3],bins=20)

In [ ]:
plt.hist(df['Fare'],bins=20)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
df_minmax=pd.DataFrame(min_max.fit_transform(X_train))
df_minmax.head()

In [ ]:
import seaborn as sns
sns.pairplot(df_minmax)

In [ ]:
plt.hist(df_minmax['Pclass'],bins=20)

In [ ]:
plt.hist(df_minmax['Age'],bins=20)