In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("winequality-white.csv", sep = ";")

In [3]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [4]:
df.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

In [6]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000
mean,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909
std,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621,0.885639
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.991723,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.993740,3.180000,0.470000,10.400000,6.000000
75%,7.300000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996100,3.280000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

In [7]:
df.head(51)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.70,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.60,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.90,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.50,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.50,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
5,8.1,0.28,0.40,6.90,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
6,6.2,0.32,0.16,7.00,0.045,30.0,136.0,0.9949,3.18,0.47,9.6,6
7,7.0,0.27,0.36,20.70,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
8,6.3,0.30,0.34,1.60,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
9,8.1,0.22,0.43,1.50,0.044,28.0,129.0,0.9938,3.22,0.45,11.0,6
10,8.1,0.27,0.41,1.45,0.033,11.0,63.0,0.9908,2.99,0.56,12.0,5
11,8.6,0.23,0.40,4.20,0.035,17.0,109.0,0.9947,3.14,0.53,9.7,5
12,7.9,0.18,0.37,1.20,0.040,16.0,75.0,0.9920,3.18,0.63,10.8,5
13,6.6,0.16,0.40,1.50,0.044,48.0,143.0,0.9912,3.54,0.52,12.4,7
14,8.3,0.42,0.62,19.25,0.040,41.0,172.0,1.0002,2.98,0.67,9.7,5
15,6.6,0.17,0.38,1.50,0.032,28.0,112.0,0.9914,3.25,0.55,11.4,7
16,6.3,0.48,0.04,1.10,0.046,30.0,99.0,0.9928,3.24,0.36,9.6,6
17,6.2,0.66,0.48,1.20,0.029,29.0,75.0,0.9892,3.33,0.39,12.8,8
18,7.4,0.34,0.42,1.10,0.033,17.0,171.0,0.9917,3.12,0.53,11.3,6
19,6.5,0.31,0.14,7.50,0.044,34.0,133.0,0.9955,3.22,0.50,9.5,5
20,6.2,0.66,0.48,1.20,0.029,29.0,75.0,0.9892,3.33,0.39,12.8,8
21,6.4,0.31,0.38,2.90,0.038,19.0,102.0,0.9912,3.17,0.35,11.0,7
22,6.8,0.26,0.42,1.70,0.049,41.0,122.0,0.9930,3.47,0.48,10.5,8
23,7.6,0.67,0.14,1.50,0.074,25.0,168.0,0.9937,3.05,0.51,9.3,5
24,6.6,0.27,0.41,1.30,0.052,16.0,142.0,0.9951,3.42,0.47,10.0,6
25,7.0,0.25,0.32,9.00,0.046,56.0,245.0,0.9955,3.25,0.50,10.4,6
26,6.9,0.24,0.35,1.00,0.052,35.0,146.0,0.9930,3.45,0.44,10.0,6
27,7.0,0.28,0.39,8.70,0.051,32.0,141.0,0.9961,3.38,0.53,10.5,6
28,7.4,0.27,0.48,1.10,0.047,17.0,132.0,0.9914,3.19,0.49,11.6,6
29,7.2,0.32,0.36,2.00,0.033,37.0,114.0,0.9906,3.10,0.71,12.3,7
30,8.5,0.24,0.39,10.40,0.044,20.0,142.0,0.9974,3.20,0.53,10.0,6
31,8.3,0.14,0.34,1.10,0.042,7.0,47.0,0.9934,3.47,0.40,10.2,6
32,7.4,0.25,0.36,2.05,0.050,31.0,100.0,0.9920,3.19,0.44,10.8,6
33,6.2,0.12,0.34,1.50,0.045,43.0,117.0,0.9939,3.42,0.51,9.0,6
34,5.8,0.27,0.20,14.95,0.044,22.0,179.0,0.9962,3.37,0.37,10.2,5
35,7.3,0.28,0.43,1.70,0.080,21.0,123.0,0.9905,3.19,0.42,12.8,5
36,6.5,0.39,0.23,5.40,0.051,25.0,149.0,0.9934,3.24,0.35,10.0,5
37,7.0,0.33,0.32,1.20,0.053,38.0,138.0,0.9906,3.13,0.28,11.2,6
38,7.3,0.24,0.39,17.95,0.057,45.0,149.0,0.9999,3.21,0.36,8.6,5
39,7.3,0.24,0.39,17.95,0.057,45.0,149.0,0.9999,3.21,0.36,8.6,5
40,6.7,0.23,0.39,2.50,0.172,63.0,158.0,0.9937,3.11,0.36,9.4,6
41,6.7,0.24,0.39,2.90,0.173,63.0,157.0,0.9937,3.10,0.34,9.4,6
42,7.0,0.31,0.26,7.40,0.069,28.0,160.0,0.9954,3.13,0.46,9.8,6
43,6.6,0.24,0.27,1.40,0.057,33.0,152.0,0.9934,3.22,0.56,9.5,6
44,6.7,0.23,0.26,1.40,0.060,33.0,154.0,0.9934,3.24,0.56,9.5,6
45,7.4,0.18,0.31,1.40,0.058,38.0,167.0,0.9931,3.16,0.53,10.0,7
46,6.2,0.45,0.26,4.40,0.063,63.0,206.0,0.9940,3.27,0.52,9.8,4
47,6.2,0.46,0.25,4.40,0.066,62.0,207.0,0.9939,3.25,0.52,9.8,5
48,7.0,0.31,0.26,7.40,0.069,28.0,160.0,0.9954,3.13,0.46,9.8,6
49,6.9,0.19,0.35,5.00,0.067,32.0,150.0,0.9950,3.36,0.48,9.8,5
50,7.2,0.19,0.31,1.60,0.062,31.0,173.0,0.9917,3.35,0.44,11.7,6

In [8]:
df['quality'].unique()

array([6, 5, 7, 8, 4, 3, 9], dtype=int64)

In [9]:
df.shape

(4898, 12)

In [10]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [11]:
X=df.iloc[:,:-1]
X.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9

In [12]:
y=df.iloc[:,-1]
y.head()

0    6
1    6
2    6
3    6
4    6
Name: quality, dtype: int64

In [13]:
from time import time
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [14]:
model=RandomForestClassifier(n_estimators=100)

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=4)
start_time=time()
n_scores =cross_val_score(model,df.iloc[:,:-1],df.iloc[:,-1],scoring='accuracy', cv=cv, n_jobs=1)
end_time=time()

print(end_time-start_time)

37.36945676803589

In [15]:
model=RandomForestClassifier(n_estimators=100)

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=4)
start_time=time()
n_scores =cross_val_score(model,df.iloc[:,:-1],df.iloc[:,-1],scoring='accuracy', cv=cv, n_jobs=2)
end_time=time()

print(end_time-start_time)

13.57053804397583

In [16]:
model=RandomForestClassifier(n_estimators=100)

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=4)
start_time=time()
n_scores =cross_val_score(model,df.iloc[:,:-1],df.iloc[:,-1],scoring='accuracy', cv=cv, n_jobs=4)
end_time=time()

print(end_time-start_time)

8.168819904327393

In [17]:
model=RandomForestClassifier(n_estimators=100)

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=4)
start_time=time()
n_scores =cross_val_score(model,df.iloc[:,:-1],df.iloc[:,-1],scoring='accuracy', cv=cv, n_jobs=-1)
end_time=time()

print(end_time-start_time)

8.070790767669678

In [18]:
cores=[1,2,3,4,5,6,7,8,9]
for core in cores:
    model=RandomForestClassifier(n_estimators=100)
    
    cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=4)
    start_time=time()
    n_scores =cross_val_score(model,df.iloc[:,:-1],df.iloc[:,-1],scoring='accuracy', cv=cv, n_jobs=core)
    end_time=time()
    total_time=end_time-start_time
    
    print("For Cores {} Training Time was {}secs".format(core,total_time))

For Cores 1 Training Time was 37.762017011642456secs
For Cores 2 Training Time was 14.328728437423706secs
For Cores 3 Training Time was 8.509941577911377secs
For Cores 4 Training Time was 13.40835428237915secs
For Cores 5 Training Time was 8.109432458877563secs
For Cores 6 Training Time was 7.672335624694824secs
For Cores 7 Training Time was 7.782999038696289secs
For Cores 8 Training Time was 6.218389987945557secs
For Cores 9 Training Time was 6.800438642501831secs